name: Link Check

on:
  schedule:
    - cron: "23 8 * * 1"
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --exclude '^https://www\.science\.org/doi/10\.1126/science\.(1259433|aay2400)$'
            --exclude '^https://forumserver\.twoplustwo\.com/?$'
            "./**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
